name = "Sabayon"
license = "MIT"
licenselink = "https://github.com/Sabayon/sabayon-website-theme-occasional/blob/master/LICENSE.md"
description = "Sabayon website occasional theme"
homepage = "https://github.com/Sabayon/sabayon-website-theme-occasional"
tags = ["blog"]
features = ["Simple Design", "Blog"]
min_version = 0.14

[author]
  name = "mudler"
  homepage = "https://blog.mudler.pm"
